apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: saurabhbagh/my-app:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 80  
          env:
            - name: BACKEND_SERVICE_NAME
              value: my-backend